// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba.Infrastructure.Persistence;

#nullable disable

namespace Prueba.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209162747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClienteId"));

                    b.Property<string>("Identidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1L,
                            Identidad = "0801-1990-12345",
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            ClienteId = 2L,
                            Identidad = "0801-1985-67890",
                            Nombre = "María González"
                        },
                        new
                        {
                            ClienteId = 3L,
                            Identidad = "0801-1992-11111",
                            Nombre = "Carlos Rodríguez"
                        });
                });

            modelBuilder.Entity("Prueba.Domain.Entities.DetalleOrden", b =>
                {
                    b.Property<long>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("OrdenId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DetalleId");

                    b.HasIndex("OrdenId")
                        .HasDatabaseName("IX_DetalleOrden_OrdenId");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("IX_DetalleOrden_ProductoId");

                    b.ToTable("DetalleOrdenes");
                });

            modelBuilder.Entity("Prueba.Domain.Entities.Orden", b =>
                {
                    b.Property<long>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrdenId"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrdenId");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Orden_ClienteId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Prueba.Domain.Entities.Producto", b =>
                {
                    b.Property<long>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1L,
                            Descripcion = "Laptop de alto rendimiento",
                            Existencia = 50,
                            Nombre = "Laptop Dell XPS 15",
                            Precio = 1299.99m
                        },
                        new
                        {
                            ProductoId = 2L,
                            Descripcion = "Mouse ergonómico inalámbrico",
                            Existencia = 150,
                            Nombre = "Mouse Logitech MX Master 3",
                            Precio = 99.99m
                        },
                        new
                        {
                            ProductoId = 3L,
                            Descripcion = "Teclado mecánico retroiluminado",
                            Existencia = 75,
                            Nombre = "Teclado Mecánico Keychron K2",
                            Precio = 89.99m
                        },
                        new
                        {
                            ProductoId = 4L,
                            Descripcion = "Monitor 4K UHD",
                            Existencia = 30,
                            Nombre = "Monitor LG 27\" 4K",
                            Precio = 449.99m
                        },
                        new
                        {
                            ProductoId = 5L,
                            Descripcion = "Webcam Full HD 1080p",
                            Existencia = 100,
                            Nombre = "Webcam Logitech C920",
                            Precio = 79.99m
                        });
                });

            modelBuilder.Entity("Prueba.Domain.Entities.DetalleOrden", b =>
                {
                    b.HasOne("Prueba.Domain.Entities.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prueba.Domain.Entities.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Prueba.Domain.Entities.Orden", b =>
                {
                    b.HasOne("Prueba.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Prueba.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("Prueba.Domain.Entities.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Prueba.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
